repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
  - repo: https://github.com/andykenward/commitlint-pre-commit-hook
    rev: e3bebb96bcaf0b0f4821f5d50b0be517f5502a44
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.16.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(mjs|jsx|js|ts|tsx?)$
        additional_dependencies:
          [
            "@typescript-eslint/eslint-plugin@1.10.2",
            "@typescript-eslint/parser@1.10.2",
            babel-eslint@10.0.1,
            eslint@5.16.0,
            eslint-config-prettier@4.3.0,
            eslint-config-react-app@4.0.1,
            eslint-plugin-flowtype@2.50.3,
            eslint-plugin-import@2.17.3,
            eslint-plugin-jest@22.6.4,
            eslint-plugin-jsx-a11y@6.2.1,
            eslint-plugin-prettier@3.1.0,
            eslint-plugin-react@7.13.0,
            eslint-plugin-react-hooks@1.6.0,
            prettier@1.18.2,
            typescript@3.5.1,
          ]
