name: Lighthouse
on: 
  deployment:
    branches:
      - staging
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .lighthouseci
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }}
          branch: ${{ github.ref }}
          urls: 'https://andykenwardcom-git-staging.andykenward.now.sh/'
          sha: ${{ github.sha }}
          outputDirectory: .lighthouseci
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Lighthouse report
          path: .lighthouseci