name: Main
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: "14"
    - name: Use npm v7
      run: sudo npm install -g npm@7.x.x
    - name: install
      run: npm -v; npm ci
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
