name: Main
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - staging
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Setup Node 10.17.x
      uses: actions/setup-node@v1.1.0
      with:
        node-version: "10.17.x"       
    - uses: actions/cache@v1.1.0
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm ci
    - name: codegen
      run: npm run codegen
      env:
        SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:ci
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: coverage
        path: coverage

  coverage:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Download coverage from checks
        uses: actions/download-artifact@v1.0.0
        with:
          name: coverage
      - uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}

    
