name: Main
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - staging
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node 10.17.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.17.x"       
    - name: info
      run: |
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm ci
    - name: codegen
      run: npm run codegen
      env:
        SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:ci
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage

  coverage:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@master
      - name: Download coverage from checks
        uses: actions/download-artifact@v1
        with:
          name: coverage
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
    
  deploy:
    runs-on: ubuntu-latest
    needs: checks
    steps:
    - uses: actions/checkout@master
    - name: Setup Node 10.17.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.17.x"    
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: deploy production
      if: github.ref == 'refs/heads/master' 
      run: npx now --no-clipboard --token ${{ secrets.ZEIT_TOKEN }} -m commit=${{ github.sha }} -m branch=${{ github.ref }} --prod --force
    - name: deploy
      if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
      run: npx now --no-clipboard --token ${{ secrets.ZEIT_TOKEN }} -m commit=${{ github.sha }} -m branch=${{ github.ref }}
    - uses: iam4x/now-deploy-preview-comment@v1.0.2
      if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}

    
