name: Main
on:
  push:
    branches: 
      - master
      - test
      - develop
  pull_request:
    branches: 
      - master
      - test
      - develop

jobs:        
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node 10.17.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.17.x"        
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm ci
    - name: codegen
      run: npm run codegen
      env:
        SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:ci

    - name: deploy production
      if: github.ref == 'refs/heads/master'
      run: now --token ${{ secrets.ZEIT_TOKEN }} -m commit=${GITHUB_SHA} -m branch=${GITHUB_REF} --target production
    - name: deploy
      if: github.ref != 'refs/heads/master'
      run: now --token ${{ secrets.ZEIT_TOKEN }} -m commit=${GITHUB_SHA} -m branch=${GITHUB_REF}
