name: Check Pull Request
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - test
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node 10.16.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.16.x"
    - name: install
      run: npm ci
    - name: codegen
      run: npm run codegen
      env:
        SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:ci
    - name: coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
