name: Main
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - test
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${GITHUB_REF}
    - uses: actions/checkout@master
    - name: Setup Node 10.17.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.17.x"       
    - name: info
      run: |
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm ci
    - name: codegen
      run: npm run codegen
      env:
        SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    needs: checks
    steps:
    - run: echo ${{github.ref}}
    - run: echo ${GITHUB_REF}
    - uses: actions/checkout@master
    - name: Setup Node 10.17.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.17.x"    
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: deploy production
      if: github.ref == 'refs/heads/master' 
      run: npx now --token ${{ secrets.ZEIT_TOKEN }} -m githubRepo=${GITHUB_REPOSITORY} -m githubCommitSha=${GITHUB_SHA} -m githubCommitRef=${GITHUB_REF} --prod --force
      env:
        GITHUB_SHA: G
    - name: deploy
      if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
      run: npx now --token ${{ secrets.ZEIT_TOKEN }} -m githubRepo=${GITHUB_REPOSITORY} -m githubCommitSha=${GITHUB_SHA} -m githubCommitRef=${GITHUB_REF}  

    
